// Command codemode shows the "code mode" pattern with gomonty: instead of the
// model calling tools one at a time, it writes a short Python program that
// calls several tools, and the host runs that program in the Monty sandbox.
//
// Each Go tool is registered as a monty.ExternalFunction. When the sandboxed
// code calls one, Monty pauses, gomonty invokes the Go function, and execution
// resumes with its result. The Python below is hard-coded where a real agent
// would paste model output, so the example runs offline.
package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"log/slog"
	"os"
	"time"

	monty "github.com/mdfranz/gomonty"
	"github.com/mdfranz/gomonty/vfs"
)

// modelCode stands in for a program generated by an LLM.
const modelCode = `
from pathlib import Path

orders = Path('/data/orders.csv').read_text().strip().splitlines()[1:]

totals = {}
for line in orders:
    customer, amount = line.split(',')
    totals[customer] = totals.get(customer, 0) + int(amount)

best = max(totals, key=lambda name: totals[name])
Path('/out/report.txt').write_text(f'{best}: {totals[best]}')

print('top customer:', best)
lookup_email(best)
`

func main() {
	if err := run(os.Stdout); err != nil {
		log.Fatal(err)
	}
}

func run(out io.Writer) error {
	// The sandbox only sees this in-memory filesystem, never the host disk.
	fs := vfs.NewMemoryFS()
	fs.AddText("/data/orders.csv", "customer,amount\nada,30\nlin,12\nada,25\nlin,40\n")
	_ = fs.Mkdir("/out", true, true)

	tools := map[string]monty.ExternalFunction{
		"lookup_email": func(_ context.Context, call monty.Call) (monty.Result, error) {
			name, ok := call.Args[0].Raw().(string)
			if !ok {
				return monty.Raise(monty.Exception{Type: "TypeError"}), nil
			}
			return monty.Return(monty.String(name + "@example.com")), nil
		},
	}

	runner, err := monty.New(modelCode, monty.CompileOptions{ScriptName: "model.py"})
	if err != nil {
		return err
	}

	logger := slog.New(slog.NewTextHandler(out, &slog.HandlerOptions{Level: slog.LevelInfo}))

	value, err := runner.Run(context.Background(), monty.RunOptions{
		Functions: tools,
		OS:        vfs.Handler(fs, vfs.MapEnvironment{}),
		Print:     monty.WriterPrintCallback(out),
		// Generated code is untrusted: bound time, memory and host-call count.
		Limits: &monty.ResourceLimits{
			MaxDuration:    2 * time.Second,
			MaxMemory:      16 << 20,
			MaxSuspensions: 100,
		},
		Telemetry: monty.SlogHandler{Logger: logger},
	})
	if err != nil {
		return err
	}
	fmt.Fprintln(out, "result:", value.Raw())

	report, err := fs.ReadText("/out/report.txt")
	if err != nil {
		return err
	}
	fmt.Fprintln(out, "report file:", report)
	return nil
}
